package com.oop.project.service.impl;

import com.oop.project.model.Order;
import com.oop.project.service.interfaces.OrderService;
import com.oop.project.service.interfaces.BillingService;
import com.oop.project.service.interfaces.CouponService;
import com.oop.project.service.interfaces.ItemService;
import com.oop.project.exception.ServiceException;
import com.oop.project.exception.ValidationException;
import com.oop.project.util.Validator;
// import com.oop.project.repository.OrderRepository; // Uncomment Week 4
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.*;

/**
 * Implementation of OrderService interface.
 * Handles order creation, status management, and cancellation with audit logging.
 * 
 * NOTE: Uses stub data for Week 1-3. Integrate with Repository in Week 4.
 * 
 * @author Service Team 
 * @version 1.0
 */
public class OrderServiceImpl implements OrderService {
    
    // TODO Week 4: Inject repositories and services via constructor
    // private final OrderRepository orderRepository;
    private final BillingService billingService;
    private final CouponService couponService;
    private final ItemService itemService;
    
    /**
     * Constructor with service dependencies.
     * TODO Week 4: Add OrderRepository parameter
     */
    public OrderServiceImpl(BillingService billingService, 
                          CouponService couponService,
                          ItemService itemService) {
        this.billingService = billingService;
        this.couponService = couponService;
        this.itemService = itemService;
    }
    
    /**
     * Creates a new order with items and optional coupon.
     * 
     * @param customerId the customer placing the order
     * @param items Map of item SKU to quantity
     * @param couponCode optional coupon code (can be null)
     * @return the created Order object
     * @throws ServiceException if validation fails or stock insufficient
     */
    @Override
    public Order createOrder(int customerId, Map<String, Integer> items, String couponCode) 
            throws ServiceException {
        try {
            // Validate inputs
            Validator.validatePositiveId(customerId, "Customer ID");
            if (items == null || items.isEmpty()) {
                throw new ValidationException("Items cannot be empty");
            }
            
            // Validate stock availability for all items
            for (Map.Entry<String, Integer> entry : items.entrySet()) {
                String sku = entry.getKey();
                int quantity = entry.getValue();
                
                Validator.validateSku(sku);
                Validator.validateQuantity(quantity);
                
                if (!itemService.checkStockAvailability(sku, quantity)) {
                    throw new ServiceException("Insufficient stock for item: " + sku);
                }
            }
            
            // Calculate subtotal
            BigDecimal subtotal = calculateOrderSubtotal(items);
            
            // Apply coupon if provided
            BigDecimal discountAmount = BigDecimal.ZERO;
            String discountInfo = null;
            
            if (couponCode != null && !couponCode.trim().isEmpty()) {
                if (couponService.validateCoupon(couponCode, subtotal)) {
                    discountAmount = couponService.applyCoupon(subtotal, couponCode);
                    discountInfo = "Coupon " + couponCode + " applied";
                }
            }
            
            // Calculate final total with tax using BillingService
            BigDecimal finalTotal = billingService.computeBill(subtotal, 1, discountAmount);
            
            // Create order object
            Order order = new Order(
                0, // orderId will be generated by database
                customerId,
                couponCode,
                BillingService.TAX_RATE,
                discountAmount,
                discountInfo,
                "PENDING",
                new Timestamp(System.currentTimeMillis()),
                subtotal,
                finalTotal
            );
            
            // TODO Week 4: Save order to database
            // Order savedOrder = orderRepository.save(order);
            
            // TODO Week 4: Save order items
            // for (Map.Entry<String, Integer> entry : items.entrySet()) {
            //     orderItemRepository.save(new OrderItem(savedOrder.getOrderId(), entry.getKey(), entry.getValue()));
            // }
            
            // Update stock quantities
            for (Map.Entry<String, Integer> entry : items.entrySet()) {
                itemService.updateStock(entry.getKey(), -entry.getValue());
            }
            
            // STUB
            return order;
            
        } catch (ValidationException e) {
            throw e;
        } catch (Exception e) {
            throw new ServiceException("Failed to create order: " + e.getMessage(), e);
        }
    }
    
    /**
     * Updates the status of an order.
     * 
     * @param orderId the order ID
     * @param newStatus the new status to set
     * @return true if update successful
     * @throws ServiceException if order not found or invalid status
     */
    @Override
    public boolean updateOrderStatus(int orderId, String newStatus) throws ServiceException {
        try {
            Validator.validatePositiveId(orderId, "Order ID");
            Validator.validateOrderStatus(newStatus);
            
            // TODO Week 4: Get existing order
            // Order order = orderRepository.findById(orderId);
            // if (order == null) {
            //     throw new ServiceException("Order not found: " + orderId);
            // }
            
            // TODO Week 4: Update status
            // orderRepository.updateStatus(orderId, newStatus);
            
            // TODO Week 4: Log in audit_log
            // auditLogRepository.logAction(orderId, "UPDATE_STATUS", "Changed to " + newStatus);
            
            // STUB
            System.out.println("Order " + orderId + " status updated to " + newStatus);
            return true;
            
        } catch (ValidationException e) {
            throw e;
        } catch (Exception e) {
            throw new ServiceException("Failed to update order status: " + e.getMessage(), e);
        }
    }
    
    /**
     * Cancels an order and restores item stock.
     * 
     * @param orderId the order ID to cancel
     * @return true if cancellation successful
     * @throws ServiceException if order already paid/cancelled or not found
     */
    @Override
    public boolean cancelOrder(int orderId) throws ServiceException {
        try {
            Validator.validatePositiveId(orderId, "Order ID");
            
            // TODO Week 4: Get order and verify it's PENDING
            // Order order = orderRepository.findById(orderId);
            // if (order == null) {
            //     throw new ServiceException("Order not found: " + orderId);
            // }
            // if (!"PENDING".equals(order.getStatus())) {
            //     throw new ServiceException("Only PENDING orders can be cancelled");
            // }
            
            // TODO Week 4: Get order items to restore stock
            // List<OrderItem> orderItems = orderItemRepository.findByOrderId(orderId);
            // for (OrderItem item : orderItems) {
            //     itemService.updateStock(item.getItemSku(), item.getQuantity());
            // }
            
            // TODO Week 4: Update order status to CANCELLED
            // orderRepository.updateStatus(orderId, "CANCELLED");
            
            // TODO Week 4: Log cancellation
            // auditLogRepository.logAction(orderId, "CANCEL_ORDER", "Order cancelled");
            
            // STUB
            System.out.println("Order " + orderId + " cancelled");
            return true;
            
        } catch (ServiceException e) {
            throw e;
        } catch (Exception e) {
            throw new ServiceException("Failed to cancel order: " + e.getMessage(), e);
        }
    }
    
    /**
     * Retrieves an order by ID with complete details.
     * 
     * @param orderId the order ID
     * @return Order object if found, null otherwise
     */
    @Override
    public Order getOrderById(int orderId) {
        try {
            // TODO Week 4: return orderRepository.findById(orderId);
            
            // STUB
            return null;
        } catch (Exception e) {
            System.err.println("Error retrieving order: " + e.getMessage());
            return null;
        }
    }
    
    /**
     * Retrieves all orders in the system.
     * 
     * @return List of all orders
     */
    @Override
    public List<Order> getAllOrders() {
        try {
            // TODO Week 4: return orderRepository.findAll();
            
            // STUB
            return new ArrayList<>();
        } catch (Exception e) {
            System.err.println("Error retrieving orders: " + e.getMessage());
            return new ArrayList<>();
        }
    }
    
    @Override
    public List<Order> getOrdersByCustomer(int customerId) {
        try {
            // TODO Week 4: return orderRepository.findByCustomerId(customerId);
            return new ArrayList<>();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            return new ArrayList<>();
        }
    }
    
    @Override
    public List<Order> getOrdersByStatus(String status) {
        try {
            // TODO Week 4: return orderRepository.findByStatus(status);
            return new ArrayList<>();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            return new ArrayList<>();
        }
    }
    
    @Override
    public List<Order> getOrdersByDateRange(Timestamp startDate, Timestamp endDate) {
        try {
            // TODO Week 4: return orderRepository.findByDateRange(startDate, endDate);
            return new ArrayList<>();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            return new ArrayList<>();
        }
    }
    
    @Override
    public List<Order> searchOrders(String keyword) {
        try {
            // TODO Week 4: return orderRepository.searchByKeyword(keyword);
            return new ArrayList<>();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            return new ArrayList<>();
        }
    }
    
    @Override
    public BigDecimal calculateTotalRevenue() {
        try {
            // TODO Week 4: return orderRepository.calculateTotalRevenue();
            return BigDecimal.ZERO;
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            return BigDecimal.ZERO;
        }
    }
    
    @Override
    public int countOrdersByStatus(String status) {
        try {
            // TODO Week 4: return orderRepository.countByStatus(status);
            return 0;
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            return 0;
        }
    }
    
    @Override
    public Map<String, Object> getOrderDetailsForInvoice(int orderId) {
        try {
            // TODO Week 4: Implement full invoice details retrieval
            return new HashMap<>();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            return new HashMap<>();
        }
    }
    
    // ========== PRIVATE HELPER METHODS ==========
    
    /**
     * Calculates order subtotal from items.
     * 
     * @param items Map of SKU to quantity
     * @return subtotal amount
     */
    private BigDecimal calculateOrderSubtotal(Map<String, Integer> items) throws ServiceException {
        BigDecimal subtotal = BigDecimal.ZERO;
        
        for (Map.Entry<String, Integer> entry : items.entrySet()) {
            String sku = entry.getKey();
            int quantity = entry.getValue();
            
            // TODO Week 4: Get item price from repository
            // Item item = itemService.getItemBySku(sku);
            // if (item == null) {
            //     throw new ServiceException("Item not found: " + sku);
            // }
            // BigDecimal itemTotal = item.getUnitPrice().multiply(new BigDecimal(quantity));
            
            // STUB: Assume price of 10.00 for testing
            BigDecimal itemTotal = new BigDecimal("10.00").multiply(new BigDecimal(quantity));
            subtotal = subtotal.add(itemTotal);
        }
        
        return subtotal;
    }
}