package com.oop.project.service.interfaces;

import com.oop.project.model.Customer;
import com.oop.project.model.Order;
import com.oop.project.model.User;

import java.util.List;
import java.util.Optional;

/**
 * FR-1: Customer Management
 *
 * Handles all business logic related to customer records,
 * including CRUD operations, search, validation, and order history.
 *
 * Validation rules applied (see ValidationRules.java):
 * - Phone must match PHONE_PATTERN (Vietnamese format, 10-11 digits)
 * - Email must match EMAIL_PATTERN (RFC 5322 simplified)
 * - Name length between MIN_NAME_LENGTH and MAX_NAME_LENGTH
 *
 * @author Lan - Service Layer
 */
public interface CustomerService {

    /**
     * Retrieve all customers from the system.
     *
     * FR-1: Base list for the Customers tab (JTable).
     *
     * @return list of all Customer objects
     */
    List<Customer> getAllCustomers();

    /**
     * Find a customer by their ID.
     *
     * @param customerId  the customer's unique ID
     * @return Optional<Customer>, empty if not found
     */
    Optional<Customer> getCustomerById(int customerId);

    /**
     * Create and save a new customer record.
     *
     * FR-1.1: The system shall allow creating customer profiles.
     * FR-1.2: Validates phone number and email format before saving.
     *
     * @param customer  the Customer object to save (customerId is auto-generated by DB)
     * @return true if saved successfully, false if validation fails or DB error
     * @throws IllegalArgumentException if name, phone, or email format is invalid
     */
    boolean addCustomer(Customer customer);

    /**
     * Update an existing customer's information.
     *
     * FR-1.1: The system shall allow updating customer profiles.
     * FR-1.2: Re-validates phone and email before updating.
     *
     * @param customer  the Customer object with updated fields (must have valid customerId)
     * @return true if updated successfully
     * @throws IllegalArgumentException if customer not found or validation fails
     */
    boolean updateCustomer(Customer customer);

    /**
     * Delete a customer by ID.
     *
     * FR-1.1: The system shall allow deleting customer profiles.
     * Requires ADMIN role — caller should call checkPermission() first via AuthenticationService.
     *
     * @param customerId  the ID of the customer to delete
     * @param actor       the currently logged-in User performing the action
     * @return true if deleted successfully
     * @throws IllegalArgumentException if customer not found
     * @throws SecurityException if actor does not have ADMIN role
     */
    boolean deleteCustomer(int customerId, User actor);

    /**
     * Search customers by name or phone number (partial match supported).
     *
     * FR-1.3: The system shall allow searching customers by name or phone number.
     *
     * @param keyword  the search term (matched against customerName or phone)
     * @return list of matching Customer objects (empty list if none found)
     */
    List<Customer> searchCustomer(String keyword);

    /**
     * Get all past orders associated with a specific customer.
     *
     * FR-1.4: The system shall display all past orders associated with a customer.
     *
     * @param customerId  the customer's ID
     * @return list of Order objects belonging to the customer
     */
    List<Order> getCustomerOrderHistory(int customerId);
}
